import React, { useState } from 'react';
import { ShieldCheck, Upload, X, CheckCircle2, AlertCircle } from 'lucide-react';
import api from '../../services/api';
import { useAuth } from '../../context/AuthContext';
import { toast } from 'sonner';

interface CertificateModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const CertificateModal: React.FC<CertificateModalProps> = ({ isOpen, onClose }) => {
  const { setDeviceCertificate } = useAuth();
  const [file, setFile] = useState<File | null>(null);
  const [isUploading, setIsUploading] = useState(false);
  const [isSuccess, setIsSuccess] = useState(false);

  if (!isOpen) return null;

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      const selected = e.target.files[0];
      if (!selected.name.endsWith('.txt')) {
        toast.error('Only .txt certificate files are permitted.');
        return;
      }
      setFile(selected);
    }
  };

  const handleInstall = async () => {
    if (!file) {
      toast.error('Please select your certificate file.');
      return;
    }

    try {
      setIsUploading(true);
      const formData = new FormData();
      formData.append('certificate', file);

      const res = await api.post('/auth/install-certificate', formData, {
        headers: { 'Content-Type': 'multipart/form-data' },
      });

      if (res.data.success) {
        setDeviceCertificate(res.data.boundToken);
        setIsSuccess(true);
        toast.success('Workstation certificate verified and installed!');
        setTimeout(() => {
          setIsSuccess(false);
          setFile(null);
          onClose();
        }, 1200);
      }
    } catch (error: any) {
      toast.error(error.response?.data?.message || 'Failed to install certificate.');
    } finally {
      setIsUploading(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/60 backdrop-blur-sm p-4">
      <div className="bg-white rounded-2xl shadow-2xl border border-slate-200 max-w-md w-full overflow-hidden animate-in fade-in zoom-in-95 duration-200">
        <div className="bg-slate-900 p-6 text-white flex justify-between items-center">
          <div className="flex items-center space-x-3">
            <div className="p-2.5 bg-slate-800 rounded-xl border border-slate-700">
              <ShieldCheck className="w-6 h-6 text-white" />
            </div>
            <div>
              <h3 className="text-lg font-bold">Install Device Certificate</h3>
              <p className="text-xs text-slate-400">Hardware-Bound 2FA Authentication</p>
            </div>
          </div>
          <button onClick={onClose} className="text-slate-300 hover:text-white p-1 rounded-lg hover:bg-white/10 transition">
            <X className="w-5 h-5 text-current" />
          </button>
        </div>

        <div className="p-6 space-y-5">
          {isSuccess ? (
            <div className="text-center py-6 space-y-3">
              <CheckCircle2 className="w-12 h-12 text-slate-900 mx-auto animate-bounce" />
              <h4 className="text-lg font-bold text-slate-800">Certificate Installed!</h4>
              <p className="text-xs text-slate-500">Your browser and workstation have been securely bound.</p>
            </div>
          ) : (
            <>
              <div className="p-4 bg-slate-100 rounded-xl border border-slate-200 flex items-start space-x-3">
                <AlertCircle className="w-5 h-5 text-slate-700 shrink-0 mt-0.5" />
                <p className="text-xs text-slate-800 leading-relaxed">
                  Upload your authorized <strong>.txt</strong> certificate key generated by the Panacea Administrator. This locks and validates access on this specific computer.
                </p>
              </div>

              <div className="border-2 border-dashed border-slate-300 rounded-xl p-6 text-center hover:border-slate-900 transition bg-slate-50/50">
                <input
                  type="file"
                  id="certFileInput"
                  accept=".txt"
                  className="hidden"
                  onChange={handleFileChange}
                />
                <label htmlFor="certFileInput" className="cursor-pointer flex flex-col items-center space-y-2">
                  <div className="w-12 h-12 bg-white rounded-full shadow-2xs flex items-center justify-center text-slate-700 border border-slate-200">
                    <Upload className="w-5 h-5 text-current" />
                  </div>
                  <span className="text-sm font-semibold text-slate-700">
                    {file ? file.name : 'Click to select certificate file'}
                  </span>
                  <span className="text-xs text-slate-400">Supports (.txt) issued certificate</span>
                </label>
              </div>

              <div className="flex justify-end space-x-3 pt-2">
                <button
                  type="button"
                  onClick={onClose}
                  className="px-4 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-100 rounded-xl transition"
                >
                  Cancel
                </button>
                <button
                  type="button"
                  disabled={!file || isUploading}
                  onClick={handleInstall}
                  className="px-5 py-2 text-xs font-semibold text-white bg-sky-600 hover:bg-sky-700 rounded-xl shadow-xs transition disabled:opacity-50 flex items-center space-x-2"
                >
                  {isUploading ? <span>Verifying...</span> : <span>Install & Bind</span>}
                </button>
              </div>
            </>
          )}
        </div>
      </div>
    </div>
  );
};
